<?php
/* Mpesa variable*/
return[

 'SHORTCODE'=>env('SHORT_CODE'),
 'CONSUMER_KEY'=>env('CONSUMER_KEY'),
 'CONSUMER_SECRET'=>env('CONSUMER_SECRET'),
 'PASS_KEY'=>env('PASS_KEY'),
 'CONFIRMATION_KEY'=>env('CONFIRMATION_KEY'),
 'VALIDATION_KEY'=>env('VALIDATION_KEY'),


];
