<?php
/* Mpesa variable*/
return[

 'SHORTCODE'=>env('MPESA_SHORTCODE'),
 'CONSUMER_KEY'=>env('MPESA_CONSUMER_KEY'),
 'CONSUMER_SECRET'=>env('MPESA_CONSUMER_SECRET'),
 'AUTHORIZATION_KEY'=>env('MPESA_AUTHORIZATION'),
 'STK_SHORTCODE'=>env('MPESA_STK_SHORTCODE'),
 'MPESA_ENV'=>env('MPESA_ENV'),
 'MPESA_MSSDN'=>env('MPESA_MSSDN'),
 'MPESA_URL'=>env('MPESA_URL'),
 'MPESA_PASSKEY'=>env('MPESA_PASSKEY'),
 'MPESA_B2C_PASSWORD'=>env('MPESA_B2C_PASSWORD'),
 'MPESA_CONFIRM_KEY'=>env('MPESA_CONFIRM_KEY'),
 'MPESA_VALIDATE_KEY'=>env('MPESA_VALIDATE_KEY'),


];
